### ISSUE TITLE
编译运行后，报这个错。librust.so找不到

### ISSUE THREAD

**Issue by jeffreyxuworld** [niuhuan/jasmine#89]
Launching lib\main.dart on Pixel 4 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime(29602): FATAL EXCEPTION: main
E/AndroidRuntime(29602): Process: opensource.jasmine, PID: 29602
E/AndroidRuntime(29602): java.lang.UnsatisfiedLinkError: dlopen failed: library "librust.so" not found
E/AndroidRuntime(29602): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/AndroidRuntime(29602): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/AndroidRuntime(29602): 	at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime(29602): 	at opensource.jenny.Jni.<clinit>(Jni.java:10)
E/AndroidRuntime(29602): 	at opensource.jasmine.MainActivity.configureFlutterEngine(MainActivity.kt:31)
E/AndroidRuntime(29602): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:214)
E/AndroidRuntime(29602): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:641)
E/AndroidRuntime(29602): 	at android.app.Activity.performCreate(Activity.java:8290)
E/AndroidRuntime(29602): 	at android.app.Activity.performCreate(Activity.java:8269)
E/AndroidRuntime(29602): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/AndroidRuntime(29602): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
E/AndroidRuntime(29602): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
E/AndroidRuntime(29602): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(29602): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(29602): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(29602): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(29602): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29602): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(29602): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(29602): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(29602): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29602): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(29602): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by niuhuan** [comment]
这个仓库已经废弃, 不建议学习, ffi错误比较多，不同平台适配困难。

您可以去pansy查看最新的代码，能更好的融合rust和flutter

https://github.com/niuhuan/pansy

**Comment by niuhuan** [comment]
flutter_rust_bridge具有丰富的文档资料和更多的人维护

https://cjycode.com/flutter_rust_bridge/feature.html

https://github.com/fzyzcjy/flutter_rust_bridge

https://github.com/Desdaemon/flutter_rust_bridge_template

此外，您有兴趣可以对pansy进行PR

https://github.com/niuhuan/pansy/issues/5

**Comment by jeffreyxuworld** [comment]
好的，谢谢
